--纳税汇总表
ALTER PROC sp_SCS_TaxReport
	@Year INT
AS
BEGIN
	CREATE TABLE #TEMP(
		FMonthName VARCHAR(255),
		FMonth INT,
		
		FSJZZS DECIMAL(28,10) DEFAULT 0,--增值税&实缴
		FYJZZS DECIMAL(28,10) DEFAULT 0,--增值税&应缴
		FSJZZSJJDJ DECIMAL(28,10) DEFAULT 0,--增值税加计抵减&实缴
		FYJZZSJJDJ DECIMAL(28,10) DEFAULT 0,--增值税加计抵减&应缴
		FSJCJS DECIMAL(28,10) DEFAULT 0,--城建税&实缴
		FYJCJS DECIMAL(28,10) DEFAULT 0,--城建税&应缴
		FSJJYFJ DECIMAL(28,10) DEFAULT 0,--教育附加&实缴
		FYJJYFJ DECIMAL(28,10) DEFAULT 0,--教育附加&应缴
		FSJSDS DECIMAL(28,10) DEFAULT 0,--所得税&实缴
		FYJSDS DECIMAL(28,10) DEFAULT 0,--所得税&应缴
		FSJJKGS DECIMAL(28,10) DEFAULT 0,--进口关税&实缴
		FYJJKGS DECIMAL(28,10) DEFAULT 0,--进口关税&应缴
		FSJYHS DECIMAL(28,10) DEFAULT 0,--印花税&实缴
		FYJYHS DECIMAL(28,10) DEFAULT 0,--印花税&应缴
		FSJGS DECIMAL(28,10) DEFAULT 0,--个税&实缴
		FYJGS DECIMAL(28,10) DEFAULT 0,--个税&应缴
		FSJDKDJSDS DECIMAL(28,10) DEFAULT 0,--代扣代缴所得税&实缴
		FYJDKDJSDS DECIMAL(28,10) DEFAULT 0,--代扣代缴所得税&应缴
		FSJQCGSHHJ DECIMAL(28,10) DEFAULT 0,--去除个税后合计&实缴
		FYJQCGSHHJ DECIMAL(28,10) DEFAULT 0,--去除个税后合计&应缴
		FSJSYSXHJ DECIMAL(28,10) DEFAULT 0,--所有税项合计&实缴
		FYJSYSXHJ DECIMAL(28,10) DEFAULT 0,--所有税项合计&应缴
	)

	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '1月份',1
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '2月份',2
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '3月份',3
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '4月份',4
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '5月份',5
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '6月份',6
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '7月份',7
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '8月份',8
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '9月份',9
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '10月份',10
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '11月份',11
	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '12月份',12

	INSERT INTO #TEMP(FMonthName,FMonth) SELECT '合计',0

	CREATE TABLE #Acct(
		FAcctID INT,
		FAcctNo VARCHAR(255),
		FLevel INT,
		FParentID INT,
		FLeve12ParentID INT,
		FLeve12ParentNo VARCHAR(255),
		FLeve13ParentNo VARCHAR(255),
		FLeve14ParentNo VARCHAR(255),
	)

	INSERT INTO #Acct
	SELECT FACCtID,FNUMBER,FLEVEL,FPARENTID,FACCtID,FNUMBER,'',''
	  FROM T_BD_ACCOUNT A
	 WHERE A.FLEVEL = 2
	   AND A.FNUMBER IN ('2221.17','2221.20','2221.07','2221.11','2221.05','2221.15'
	   ,'2221.14','2221.13')

	INSERT INTO #Acct
	SELECT FACCtID,FNUMBER,FLEVEL,FPARENTID,FACCtID,FNUMBER,'',''
	  FROM T_BD_ACCOUNT A
	 WHERE A.FLEVEL = 3
	   AND A.FNUMBER IN ('2221.18.04')

	INSERT INTO #Acct
	SELECT  A.FACCtID,A.FNUMBER,A.FLEVEL,A.FPARENTID,B.FLeve12ParentID,FLeve12ParentNo,A.FNUMBER,''
	  FROM  T_BD_ACCOUNT A
			INNER JOIN #Acct B
			ON A.FPARENTID = B.FACCtID
	 WHERE  A.FLEVEL = 3

	INSERT INTO #Acct
	SELECT  A.FACCtID,A.FNUMBER,A.FLEVEL,A.FPARENTID,B.FLeve12ParentID,FLeve12ParentNo,A.FNUMBER,''
	  FROM  T_BD_ACCOUNT A
			INNER JOIN #Acct B
			ON A.FPARENTID = B.FACCtID
	 WHERE  A.FLEVEL = 4

	INSERT INTO #Acct
	SELECT  A.FACCtID,A.FNUMBER,A.FLEVEL,A.FPARENTID,B.FLeve12ParentID,FLeve12ParentNo,FLeve13ParentNo,A.FNUMBER
	  FROM  T_BD_ACCOUNT A
			INNER JOIN #Acct B
			ON A.FPARENTID = B.FACCtID
	 WHERE  A.FLEVEL = 5

	SELECT  A.FYEAR,A.FPERIOD,H.FLeve12ParentNo,SUM(A.FCREDIT)FCREDIT,SUM(A.FDEBIT)FDEBIT
	  INTO  #Balance
	  FROM  T_GL_Balance A
			INNER JOIN T_BD_ACCOUNT B
			ON B.FACCTID = A.FACCOUNTID
			INNER JOIN #Acct H
			ON A.FACCOUNTID = H.FAcctID
	 WHERE  1=1   
	   AND  ((A.FYEAR = @Year AND @Year <> '' ) OR @Year = '')
	   AND  A.FACCOUNTID IN (SELECT FAcctID FROM #Acct)
	   AND  A.FCURRENCYID <> 0
	 GROUP  BY H.FLeve12ParentNo,A.FYEAR,A.FPERIOD

	DECLARE @Period INT
	SET @Period = 0
	WHILE (@Period <= 12)
	BEGIN
		SET @Period = @Period + 1

		UPDATE #TEMP SET FSJZZS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.17')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJZZS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.17')),0)
		WHERE FMonth = @Period


	   UPDATE #TEMP SET FSJZZSJJDJ = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.20')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJZZSJJDJ = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.20')),0)
		WHERE FMonth = @Period

	   UPDATE #TEMP SET FSJCJS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.07')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJCJS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.07')),0)
		WHERE FMonth = @Period

	   UPDATE #TEMP SET FSJJYFJ = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.11')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJJYFJ = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.11')),0)
		WHERE FMonth = @Period

		UPDATE #TEMP SET FSJSDS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.05')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJSDS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.05')),0)
		WHERE FMonth = @Period

		UPDATE #TEMP SET FSJJKGS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.15')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJJKGS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.15')),0)
		WHERE FMonth = @Period

		UPDATE #TEMP SET FSJYHS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.14')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJYHS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.14')),0)
		WHERE FMonth = @Period

		UPDATE #TEMP SET FSJGS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.13')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJGS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.13')),0)
		WHERE FMonth = @Period

		UPDATE #TEMP SET FSJDKDJSDS = ISNULL((
			SELECT SUM(FDEBIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.18.04')),0)
		WHERE FMonth = @Period

	    UPDATE #TEMP SET FYJDKDJSDS = ISNULL((
			SELECT SUM(FCREDIT) FROM #Balance 
			 WHERE FYEAR = @Year AND FPERIOD = @Period AND FLeve12ParentNo IN ('2221.18.04')),0)
		WHERE FMonth = @Period

	END
	select*from #TEMP

	--更新去除个税后合计，所有税项合计
	UPDATE #TEMP SET FSJQCGSHHJ = FSJZZS-FSJZZSJJDJ+FSJCJS+FSJJYFJ+FSJSDS+FSJJKGS+FSJYHS+FSJDKDJSDS
	UPDATE #TEMP SET FYJQCGSHHJ = FYJZZS-FYJZZSJJDJ+FYJCJS+FYJJYFJ+FYJSDS+FYJJKGS+FYJYHS+FYJDKDJSDS
	UPDATE #TEMP SET FSJSYSXHJ = FSJZZS-FSJZZSJJDJ+FSJCJS+FSJJYFJ+FSJSDS+FSJJKGS+FSJYHS+FSJGS+FSJDKDJSDS
	UPDATE #TEMP SET FYJSYSXHJ = FYJZZS-FYJZZSJJDJ+FYJCJS+FYJJYFJ+FYJSDS+FYJJKGS+FYJYHS+FYJGS+FYJDKDJSDS

	--更新今年合计
	UPDATE #TEMP SET FSJZZS = (SELECT SUM(FSJZZS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJZZS = (SELECT SUM(FYJZZS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJZZSJJDJ = (SELECT SUM(FSJZZSJJDJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJZZSJJDJ = (SELECT SUM(FYJZZSJJDJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJCJS = (SELECT SUM(FSJCJS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJCJS = (SELECT SUM(FYJCJS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJJYFJ = (SELECT SUM(FSJJYFJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJJYFJ = (SELECT SUM(FYJJYFJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJSDS = (SELECT SUM(FSJSDS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJSDS = (SELECT SUM(FYJSDS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJJKGS = (SELECT SUM(FSJJKGS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJJKGS = (SELECT SUM(FYJJKGS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJYHS = (SELECT SUM(FSJYHS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJYHS = (SELECT SUM(FYJYHS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJGS = (SELECT SUM(FSJGS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJGS = (SELECT SUM(FYJGS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJDKDJSDS = (SELECT SUM(FSJDKDJSDS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJDKDJSDS = (SELECT SUM(FYJDKDJSDS) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJQCGSHHJ = (SELECT SUM(FSJQCGSHHJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJQCGSHHJ = (SELECT SUM(FYJQCGSHHJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FSJSYSXHJ = (SELECT SUM(FSJSYSXHJ) FROM #TEMP) WHERE FMonthName = '合计'
	UPDATE #TEMP SET FYJSYSXHJ = (SELECT SUM(FYJSYSXHJ) FROM #TEMP) WHERE FMonthName = '合计'

	SELECT * FROM #TEMP
END