--完工项目成本报表
--EXEC sp_YJ_ProgramCost 2020,1,2023,12,'',''
ALTER PROC sp_YJ_ProgramCost
	@BeginYear INT,
	@BeginPeriod INT,
	@EndYear INT,
	@EndPeriod INT,
	@ProgramNo VARCHAR(MAX),
	@ProgramGroup VARCHAR(255),
	@TempTable VARCHAR(255) = ''
AS
BEGIN

	IF(@BeginYear = '')
	BEGIN
		SET @BeginYear = 2010
	END
	IF(@BeginPeriod = '')
	BEGIN
		SET @BeginPeriod = 1
	END
	IF(@EndYear = '')
	BEGIN
		SET @EndYear = 2030
	END
	IF(@EndPeriod = '')
	BEGIN
		SET @EndPeriod = 12
	END

	DECLARE @BeginYearPeriod INT
	DECLARE @EndYearPeriod INT
	DECLARE @BeginTime VARCHAR(255)
	DECLARE @EndTime VARCHAR(255)
	SET @BeginYearPeriod = @BeginYear * 100 + @BeginPeriod
	SET @EndYearPeriod = @EndYear * 100 + @EndPeriod

	SET @BeginTime = CONVERT(VARCHAR(4),@BeginYear) + '-' + CONVERT(VARCHAR(2),@BeginPeriod) + '-01'
	IF(@BeginPeriod < 10)
	BEGIN
		SET @BeginTime = CONVERT(VARCHAR(4),@BeginYear) + '-0' + CONVERT(VARCHAR(1),@BeginPeriod) + '-01'
	END

	SET @EndTime = CONVERT(VARCHAR(4),@EndYear) + '-' + CONVERT(VARCHAR(2),@EndPeriod) + '-01'
	IF(@EndPeriod < 10)
	BEGIN
		SET @EndTime = CONVERT(VARCHAR(4),@EndYear) + '-0' + CONVERT(VARCHAR(1),@EndPeriod) + '-01'
	END
	SET @EndTime = CONVERT(VARCHAR(10),DATEADD(MONTH,1,@EndTime),120)

	CREATE TABLE #TEMP(
		项目号 VARCHAR(255),
		项目名称 VARCHAR(255),
		项目类型 VARCHAR(255),
		项目年份 VARCHAR(255),
		机械分包部分 DECIMAL(28,2) DEFAULT 0,
		加工费 DECIMAL(28,2) DEFAULT 0,
		材料费 DECIMAL(28,2) DEFAULT 0,
		分包费 DECIMAL(28,2) DEFAULT 0,
		[雾化器、雾化盘、喷嘴部分] DECIMAL(28,2) DEFAULT 0,
		差旅费 DECIMAL(28,2) DEFAULT 0,
		机械外购件部分 DECIMAL(28,2) DEFAULT 0,
		电气分包部分 DECIMAL(28,2) DEFAULT 0,
		运输包装 DECIMAL(28,2) DEFAULT 0,
		间接费 DECIMAL(28,2) DEFAULT 0,
		预估成本 DECIMAL(28,2) DEFAULT 0,
		其他费用 DECIMAL(28,2) DEFAULT 0,
		总计 DECIMAL(28,2) DEFAULT 0,

		机械分包部分1 DECIMAL(28,2) DEFAULT 0,
		加工费1 DECIMAL(28,2) DEFAULT 0,
		材料费1 DECIMAL(28,2) DEFAULT 0,
		分包费1 DECIMAL(28,2) DEFAULT 0,
		[雾化器、雾化盘、喷嘴部分1] DECIMAL(28,2) DEFAULT 0,
		差旅费1 DECIMAL(28,2) DEFAULT 0,
		机械外购件部分1 DECIMAL(28,2) DEFAULT 0,
		电气分包部分1 DECIMAL(28,2) DEFAULT 0,
		运输包装1 DECIMAL(28,2) DEFAULT 0,
		间接费1 DECIMAL(28,2) DEFAULT 0,
		预估成本1 DECIMAL(28,2) DEFAULT 0,
		其他费用1 DECIMAL(28,2) DEFAULT 0,
		总计1 DECIMAL(28,2) DEFAULT 0,
	)

	CREATE TABLE #TEMP1(
		F1A VARCHAR(255),
		F2A VARCHAR(255),
		F3A VARCHAR(255),
		F4A VARCHAR(255),
		F5A DECIMAL(28,2) DEFAULT 0,
		F6A DECIMAL(28,2) DEFAULT 0,
		F7A DECIMAL(28,2) DEFAULT 0,
		F8A DECIMAL(28,2) DEFAULT 0,
		F9A DECIMAL(28,2) DEFAULT 0,
		F10 DECIMAL(28,2) DEFAULT 0,
		F11 DECIMAL(28,2) DEFAULT 0,
		F12 DECIMAL(28,2) DEFAULT 0,
		F13 DECIMAL(28,2) DEFAULT 0,
		F14 DECIMAL(28,2) DEFAULT 0,
		F15 DECIMAL(28,2) DEFAULT 0,
		F16 DECIMAL(28,2) DEFAULT 0,
		F17 DECIMAL(28,2) DEFAULT 0,

		F18 DECIMAL(28,2) DEFAULT 0,
		F19 DECIMAL(28,2) DEFAULT 0,
		F20 DECIMAL(28,2) DEFAULT 0,
		F21 DECIMAL(28,2) DEFAULT 0,
		F22 DECIMAL(28,2) DEFAULT 0,
		F23 DECIMAL(28,2) DEFAULT 0,
		F24 DECIMAL(28,2) DEFAULT 0,
		F25 DECIMAL(28,2) DEFAULT 0,
		F26 DECIMAL(28,2) DEFAULT 0,
		F27 DECIMAL(28,2) DEFAULT 0,
		F28 DECIMAL(28,2) DEFAULT 0,
		F29 DECIMAL(28,2) DEFAULT 0,
		F30 DECIMAL(28,2) DEFAULT 0,
	)

	CREATE TABLE #Acct(
		FAcctID INT,
		FAcctNo VARCHAR(255),
		FLevel INT,
		FParentID INT,
		FLeve12ParentID INT,
		FLeve12ParentNo VARCHAR(255),
		FLeve13ParentNo VARCHAR(255),
	)

	INSERT INTO #Acct
	SELECT FACCtID,FNUMBER,FLEVEL,FPARENTID,FACCtID,FNUMBER,''
	  FROM T_BD_ACCOUNT A
	 WHERE A.FLEVEL = 2
	   AND A.FNUMBER IN ('5001.01','5001.02','5001.03','5001.04','5001.05','5001.06','5001.07','5001.08','5001.99')

	INSERT INTO #Acct
	SELECT  A.FACCtID,A.FNUMBER,A.FLEVEL,A.FPARENTID,B.FLeve12ParentID,FLeve12ParentNo,A.FNUMBER
	  FROM  T_BD_ACCOUNT A
			INNER JOIN #Acct B
			ON A.FPARENTID = B.FACCtID
	 WHERE  A.FLEVEL = 3

	INSERT INTO #Acct
	SELECT  A.FACCtID,A.FNUMBER,A.FLEVEL,A.FPARENTID,B.FLeve12ParentID,FLeve12ParentNo,FLeve13ParentNo
	  FROM  T_BD_ACCOUNT A
			INNER JOIN #Acct B
			ON A.FPARENTID = B.FACCtID
	 WHERE  A.FLEVEL = 4

	SELECT  D.FNUMBER FProgramNo,E.FNAME FProgramName,G.FNAME FProgramGroup
	       ,A.FAccountID,B.FNUMBER FAccountNo,SUM(A.FCREDIT)FCREDIT,SUM(A.FDEBIT)FDEBIT
	  INTO  #Balance
	  FROM  T_GL_Balance A
			INNER JOIN T_BD_ACCOUNT B
			ON B.FACCTID = A.FACCOUNTID
			INNER JOIN T_BD_FLEXITEMDETAILV C
			ON A.FDETAILID = C.FID
			INNER JOIN T_BAS_PREBDONE D
			ON C.FF100003 = D.FID
			INNER JOIN T_BAS_PREBDONE_L E
			ON C.FF100003 = E.FID AND E.FLocaleID = 2052
			LEFT JOIN T_Project F
			ON D.F_PDLJ_Group = F.FID 
			LEFT JOIN T_Project_L G
			ON D.F_PDLJ_Group = G.FID AND G.FLocaleID = 2052
	 WHERE  1=1
	   AND  ((A.FYEARPERIOD >= @BeginYearPeriod AND @BeginYearPeriod <> '' ) OR @BeginYearPeriod = '')	   
	   AND  ((A.FYEARPERIOD <= @EndYearPeriod AND @EndYearPeriod <> '' ) OR @EndYearPeriod = '')
	   AND  ((G.FNAME = @ProgramGroup AND @ProgramGroup <> '' ) OR @ProgramGroup = '')
	   AND  ((@ProgramNo <> '' AND (D.FNUMBER IN (SELECT value FROM sp_split(@ProgramNo,','))) )OR @ProgramNo = '')
	   AND  A.FACCOUNTID IN (SELECT FAcctID FROM #Acct)
	   --AND  B.FNUMBER IN ('5001.01','5001.01.01','5001.01.02','5001.01.03','5001.02','5001.03','5001.04','5001.05','5001.06','5001.07','5001.08','5001.99')
	   AND  A.FCURRENCYID <> 0
	 GROUP  BY D.FNUMBER,E.FNAME,G.FNAME,A.FACCOUNTID,B.FNUMBER

	INSERT INTO #TEMP(项目号,项目名称,项目类型)
	SELECT DISTINCT FProgramNo,FProgramName,FProgramGroup FROM #Balance

	UPDATE  A
	   SET  A.项目年份 = YEAR(B.FDATE)
	  FROM  #TEMP A
			INNER JOIN T_BAS_PREBDONE C 
			ON A.项目号 = C.FNUMBER
			INNER JOIN (SELECT FENGINEENO,MAX(FDATE)FDATE FROM PDLJ_t_Cust130007 GROUP BY FENGINEENO)B
			ON C.FID = B.FENGINEENO

	UPDATE  A
	   SET  A.机械分包部分 = ISNULL(B.FCREDIT,0)
	       ,A.加工费 = ISNULL(C.FCREDIT,0)
		   ,A.材料费 = ISNULL(D.FCREDIT,0)
		   ,A.分包费 = ISNULL(E.FCREDIT,0)
		   ,A.[雾化器、雾化盘、喷嘴部分] = ISNULL(F.FCREDIT,0)
		   ,A.差旅费 = ISNULL(G.FCREDIT,0)
		   ,A.机械外购件部分 = ISNULL(H.FCREDIT,0)
		   ,A.电气分包部分 = ISNULL(I.FCREDIT,0)
		   ,A.运输包装 = ISNULL(J.FCREDIT,0)
		   ,A.间接费 = ISNULL(K.FCREDIT,0)
		   ,A.预估成本 = ISNULL(L.FCREDIT,0)
		   ,A.其他费用 = ISNULL(M.FCREDIT,0)

		   ,A.机械分包部分1 = ISNULL(B.FDEBIT,0)
	       ,A.加工费1 = ISNULL(C.FDEBIT,0)
		   ,A.材料费1 = ISNULL(D.FDEBIT,0)
		   ,A.分包费1 = ISNULL(E.FDEBIT,0)
		   ,A.[雾化器、雾化盘、喷嘴部分1] = ISNULL(F.FDEBIT,0)
		   ,A.差旅费1 = ISNULL(G.FDEBIT,0)
		   ,A.机械外购件部分1 = ISNULL(H.FDEBIT,0)
		   ,A.电气分包部分1 = ISNULL(I.FDEBIT,0)
		   ,A.运输包装1 = ISNULL(J.FDEBIT,0)
		   ,A.间接费1 = ISNULL(K.FDEBIT,0)
		   ,A.预估成本1 = ISNULL(L.FDEBIT,0)
		   ,A.其他费用1 = ISNULL(M.FDEBIT,0)
	  FROM  #TEMP A
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.01') GROUP BY FProgramNo)B
			ON A.项目号 = B.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve13ParentNo = '5001.01.01') GROUP BY FProgramNo)C
			ON A.项目号 = C.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve13ParentNo = '5001.01.02') GROUP BY FProgramNo)D
			ON A.项目号 = D.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve13ParentNo = '5001.01.03') GROUP BY FProgramNo)E
			ON A.项目号 = E.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.02') GROUP BY FProgramNo)F
			ON A.项目号 = F.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.03') GROUP BY FProgramNo)G
			ON A.项目号 = G.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.04') GROUP BY FProgramNo)H
			ON A.项目号 = H.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.05') GROUP BY FProgramNo)I
			ON A.项目号 = I.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.06') GROUP BY FProgramNo)J
			ON A.项目号 = J.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.07') GROUP BY FProgramNo)K
			ON A.项目号 = K.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.08') GROUP BY FProgramNo)L
			ON A.项目号 = L.FProgramNo
			LEFT JOIN (SELECT FProgramNo,SUM(FCREDIT)FCREDIT,SUM(FDEBIT)FDEBIT FROM #Balance WHERE FAccountID IN (SELECT FAcctID FROM #Acct WHERE FLeve12ParentNo = '5001.99') GROUP BY FProgramNo)M
			ON A.项目号 = M.FProgramNo

	UPDATE #TEMP SET 总计 = 机械分包部分 + [雾化器、雾化盘、喷嘴部分] + 差旅费 + 机械外购件部分
	UPDATE #TEMP SET 总计 = 总计 + 电气分包部分 + 运输包装 + 间接费 + 预估成本 + 其他费用 

	UPDATE #TEMP SET 总计1 = 机械分包部分1 + [雾化器、雾化盘、喷嘴部分1] + 差旅费1 + 机械外购件部分1
	UPDATE #TEMP SET 总计1 = 总计1 + 电气分包部分1 + 运输包装1 + 间接费1 + 预估成本1 + 其他费用1

	--DELETE FROM #TEMP WHERE 总计 = 0

	INSERT INTO #TEMP1 SELECT * FROM #TEMP
	SELECT * FROM #TEMP

	IF(@TempTable <> '')
	BEGIN
		DECLARE @SQL VARCHAR(2000)
		SET @SQL = '
		SELECT ROW_NUMBER() OVER(ORDER BY F1A ASC) FIDENTITYID,* 
		  INTO '+@TempTable+'
		  FROM #TEMP1'

		EXECUTE(@SQL)
	END
END
